import requests
import streamlit as st

API_BASE = "http://127.0.0.1:8001/api/v1/documents"

st.set_page_config(page_title="AI Document Services", layout="wide")
st.title("AI Document Services")


def fetch_documents() -> list[dict]:
    try:
        resp = requests.get(f"{API_BASE}/", timeout=10)
        return resp.json() if resp.ok else []
    except Exception:
        return []


# ── Section 1: Upload & Ingest ────────────────────────────────────────────────
st.header("Upload Document")

uploaded_file = st.file_uploader("Select a PDF to upload and ingest", type=["pdf"])

if st.button("Upload & Ingest", disabled=uploaded_file is None):
    with st.spinner(f"Uploading and ingesting {uploaded_file.name} ..."):
        try:
            resp = requests.post(
                f"{API_BASE}/upload",
                files={"file": (uploaded_file.name, uploaded_file.getvalue(), "application/pdf")},
                timeout=300,
            )
        except Exception as exc:
            st.error(f"Request failed: {exc}")
            resp = None

    if resp is not None:
        if resp.ok:
            data = resp.json()
            st.success(data.get("message", "Ingestion complete"))
            st.json(data)
        else:
            st.error(f"Error {resp.status_code}: {resp.text}")

st.divider()

# ── Section 2: Ingested Documents ────────────────────────────────────────────
st.header("Ingested Documents")

col_refresh, _ = st.columns([1, 9])
if col_refresh.button("Refresh"):
    st.rerun()

documents = fetch_documents()

if not documents:
    st.info("No documents ingested yet.")
else:
    header_cols = st.columns([4, 2, 1, 1, 1])
    header_cols[0].markdown("**File Name**")
    header_cols[1].markdown("**Status**")
    header_cols[2].markdown("**Pages**")
    header_cols[3].markdown("**Scanned**")
    header_cols[4].markdown("**Action**")

    for doc in documents:
        row = st.columns([4, 2, 1, 1, 1])
        row[0].write(doc["file_name"])
        row[1].write(doc["ingestion_status"])
        row[2].write(str(doc.get("page_count") or "-"))
        row[3].write("Yes" if doc.get("is_scanned") else "No")
        if row[4].button("Delete", key=f"del_{doc['file_name']}"):
            with st.spinner(f"Deleting {doc['file_name']} ..."):
                try:
                    del_resp = requests.delete(
                        f"{API_BASE}/{doc['file_name']}", timeout=30
                    )
                except Exception as exc:
                    st.error(f"Request failed: {exc}")
                    del_resp = None
            if del_resp is not None:
                if del_resp.ok:
                    st.success(f"Deleted: {doc['file_name']}")
                    st.rerun()
                else:
                    st.error(f"Delete failed {del_resp.status_code}: {del_resp.text}")

st.divider()

# ── Section 3: Query Documents ────────────────────────────────────────────────
st.header("Query Documents")

LLM_MODELS = [
    "gpt-4o-mini",
    "gpt-4o",
    "gpt-4.1",
    "gpt-4.1-mini",
    "gpt-4.1-nano",
]

file_options = ["All documents"] + [d["file_name"] for d in documents]
col_file, col_model = st.columns([3, 1])
selected_file = col_file.selectbox("Scope search to a specific document (optional)", file_options)
selected_model = col_model.selectbox("LLM model", LLM_MODELS, index=0)

query_text = st.text_input("Enter your query")
top_k = st.slider("Number of chunks to retrieve", min_value=1, max_value=20, value=5)

if st.button("Search", disabled=not query_text.strip()):
    payload: dict = {"query": query_text, "top_k": top_k, "llm_model": selected_model}
    if selected_file != "All documents":
        payload["file_name"] = selected_file

    with st.spinner("Retrieving chunks and generating answer ..."):
        try:
            search_resp = requests.post(f"{API_BASE}/query", json=payload, timeout=120)
        except Exception as exc:
            st.error(f"Request failed: {exc}")
            search_resp = None

    if search_resp is not None:
        if search_resp.ok:
            results = search_resp.json()

            # ── LLM answer ────────────────────────────────────────────────────
            if results.get("llm_answer"):
                st.subheader("Answer")
                st.info(results["llm_answer"])
                st.caption(f"Generated by {results.get('llm_model', selected_model)}")
            else:
                st.warning("No chunks retrieved — no answer generated.")

            st.divider()

            # ── Retrieved chunks ──────────────────────────────────────────────
            st.subheader(f"Retrieved chunks ({results['total_results']})")
            for chunk in results["results"]:
                label = (
                    f"[{chunk['file_name']}]  "
                    f"Page {chunk.get('page_start', '?')}  |  "
                    f"Score: {chunk['similarity_score']:.4f}  |  "
                    f"Chunk #{chunk['chunk_sequence']}"
                )
                with st.expander(label):
                    st.text(chunk["chunk_text"])
        else:
            st.error(f"Search failed {search_resp.status_code}: {search_resp.text}")
